### ISSUE TITLE
ID motion to modify intro uses same variable twice

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-209aPlaintiffMotionToModify#55]
It doesn't break anything for the user, but it makes it untestable by automated tests

```yml
id: motion to modify intro
continue button field: a_plaintiff_s_motion_to_modify_qc_v20009_intro
fields:
  - no label: a_plaintiff_s_motion_to_modify_qc_v20009_intro
```
